name: "<npm build template>"
on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Source code clone
        uses: actions/checkout@v3
      - name: Node.js 16 (LTS) setup
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Dependencies installation
        run: yarn ci
      - name: Coding standard check
        run: yarn lint:prod
      - name: Types integrity check
        run: yarn check:types
      - name: Source code build
        run: yarn build
      - name: Artifact creation
        run: |
          PACKAGE_VERSION=`node -e "console.log(require('./package.json').version);"`
          PACKAGE_NAME="vuert-v${PACKAGE_VERSION}.tgz"
          yarn pack
          tar -xzvf "${PACKAGE_NAME}" -C "."

      - name: Artifact upload
        uses: actions/upload-artifact@v3
        with:
          name: vuert
          path: package
