name: Docs deploy
on:
  push:
    branches: [master]

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  docs-build:
    name: Docs build
    runs-on: ubuntu-latest
    steps:
      - name: Source code clone
        uses: actions/checkout@v4
      - name: Node.js 20 (LTS) setup
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Corepack activation
        run: corepack enable
      - name: Yarn installation
        run: yarn set version stable
      - name: Dependencies installation
        working-directory: packages/docs
        run: yarn ci
      - name: Coding standard check
        working-directory: packages/docs
        run: yarn lint:prod
      - name: Types integrity check
        working-directory: packages/docs
        run: yarn check:types
      - name: Source code build
        working-directory: packages/docs
        run: yarn build
      - name: Artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: byloth-vuert-docs
          path: packages/docs/dist

  docs-deploy:
    name: GitHub Pages deploy
    needs: docs-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Artifact download
        uses: actions/download-artifact@v4
        with:
          name: byloth-vuert-docs

      - name: GitHub Pages setup
        uses: actions/configure-pages@v4
      - name: Artifact upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - id: deployment
        name: GitHub Pages deployment
        uses: actions/deploy-pages@v4

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
