name: Docs deploy
on:
  push:
    branches: [master]

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  docs-build:
    name: Docs build
    runs-on: ubuntu-latest
    steps:
      - name: Cloning source code
        uses: actions/checkout@v4
      - name: "`pnpm` installation"
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Configuring Node.js 22 (LTS)
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 22

      - name: Installing dependencies
        run: pnpm run ci
      - name: Linting the source code
        run: pnpm run lint:docs
        env:
          NODE_ENV: production

      - name: Checking type consistency
        run: pnpm run typecheck:docs
      - name: Building the source code
        run: pnpm build:docs
      - name: Creating the artifact
        uses: actions/upload-artifact@v4
        with:
          name: byloth-vuert-docs
          path: packages/docs/dist

  docs-deploy:
    name: GitHub Pages deploy
    needs: docs-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Downloading the artifact
        uses: actions/download-artifact@v4
        with:
          name: byloth-vuert-docs

      - name: Configuring GitHub Pages
        uses: actions/configure-pages@v4
      - name: Uploading the GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - id: deployment
        name: Deploying GitHub Pages
        uses: actions/deploy-pages@v4

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
