name: NPM release
on:
  release:
    types: [created]

jobs:
  artifact-build:
    name: Artifact
    uses: ./.github/workflows/build-template.yml

  npm-release:
    name: NPM
    needs: artifact-build
    uses: ./.github/workflows/release-template.yml
    with:
      auth-token: ${{ secrets.NPM_TOKEN }}
