name: GPR release
on:
  release:
    types: [published]

jobs:
  deploy-gpr:
    name: GPR
    uses: ./.github/workflows/template-deploy.yml
    with:
      registry-url: https://npm.pkg.github.com/

    secrets:
      AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
