name: "<template:deploy>"
on:
  workflow_call:
    inputs:
      registry-url:
        default: https://registry.npmjs.org
        required: false
        type: string

    secrets:
      AUTH_TOKEN:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Source code clone
        uses: actions/checkout@v4
      - name: Node.js 20 (LTS) setup
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: ${{ inputs.registry-url }}

      - name: Corepack activation
        run: corepack enable
      - name: Yarn installation
        run: yarn set version stable
      - name: Dependencies installation
        run: yarn install --immutable
      - name: Coding standard check
        run: yarn lint:prod
      - name: Types integrity check
        run: yarn check:types
      - name: Source code build
        run: yarn build

      - if: ${{ github.event.release.prerelease == true }}
        name: Pre-release package publish
        run: yarn publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

      - if: ${{ github.event.release.prerelease == false }}
        name: Latest package publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
