name: "<template:deploy>"
on:
  workflow_call:
    inputs:
      registry-url:
        default: registry.npmjs.org
        required: false
        type: string

    secrets:
      AUTH_TOKEN:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Cloning source code
        uses: actions/checkout@v4
      - name: "`pnpm` installation"
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Configuring Node.js 20 (LTS)
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 20

      - name: Installing dependencies
        run: pnpm run ci
      - name: Linting the source code
        run: pnpm run lint
        env:
          NODE_ENV: production

      - name: Checking type consistency
        run: pnpm run typecheck
      - name: Building the source code
        run: pnpm build
      - name: Setting up the NPM registry
        run: |
          npm set "registry=https://${{ inputs.registry-url }}/"
          npm set "//${{ inputs.registry-url }}/:_authToken=${{ secrets.AUTH_TOKEN }}"

      - if: ${{ github.event.release.prerelease == true }}
        name: Pulishing the prerelease package
        run: lerna publish from-package --yes --pre-dist-tag next

      - if: ${{ github.event.release.prerelease == false }}
        name: Publishing the release package
        run: lerna publish from-package --yes
